// packages/microfront-core-react/src/microfront-in-shadow.tsx
import React, { useCallback } from 'react';
import { createPortal } from 'react-dom';
import { MicroFrontModuleBootstrap } from '@redneckz/microfront-core';

import { useShadow } from './use-shadow';
import { useBootstrap } from './use-bootstrap';
import { useMount } from './use-mount';

export interface MicroFrontInShadowProps {
    route?: string;

    bootstrap: MicroFrontModuleBootstrap;

    renderError?: (error: Error) => React.ReactNode;
    children: (mountingRootRef: React.RefObject<any>) => React.ReactNode;
}

/**
 * MicroFrontInShadow is responsible for the shadow DOM isolation of loaded MF.
 * It accepts "bootstrap" function produced by @redneckz/microfront-core "register" function.
 *
 * @param route - root route dedicated for remote module
 * @param bootstrap - bootstrap function provided by @redneckz/microfront-core "register" function
 * @param renderError - render something in case of bootstrap/mount/unmount error
 * @param children - kind of loading and success handler
 * @returns
 */
export function MicroFrontInShadow({ route, bootstrap, renderError = defaultErrorRenderer, children }: MicroFrontInShadowProps) {
    const [shadowRoot, rootRef] = useShadow<HTMLDivElement>();

    const bootstrapModule = useCallback(async () => {
        if (!shadowRoot) return;

        return bootstrap({ route, root: shadowRoot });
    }, [route, shadowRoot]);

    const [bootstrappedModule, error] = useBootstrap(bootstrapModule);

    const mountingRootRef = useMount(bootstrappedModule);

    const renderToShadowRoot = (children: React.ReactNode) =>
        shadowRoot ? createPortal(children, shadowRoot as any) : children;

    return (
        <div ref={rootRef} role="document" aria-atomic="true">
            {renderToShadowRoot(
                error
                    ? // handle module loading error
                      renderError(error)
                    : // render mounting root placehoder by means of render props, cause layout is up to host container
                      children(mountingRootRef)
            )}
        </div>
    );
}

function defaultErrorRenderer(error: Error): React.ReactNode {
    throw error;
}

// packages/microfront-core-vue/src/microfront-in-shadow.tsx
import { h, RenderFunction, Ref, defineComponent, ref, onMounted, onBeforeUnmount } from 'vue';
import { MicroFrontModuleBootstrap, MicroFrontBootstrappedModule } from '@redneckz/microfront-core';

import { moveToShadow } from './shadow.directive';

export interface MicroFrontInShadowProps {
    route?: string;

    bootstrap: MicroFrontModuleBootstrap;

    // Render-props pattern...
    renderError?: (error: Error) => ReturnType<RenderFunction>;
    // Can be refactored to scoped slots
    children: (mountingRootRef: Ref) => ReturnType<RenderFunction>;
}

export const MicroFrontInShadow = defineComponent(function MicroFrontInShadow({
    route,
    bootstrap,
    renderError = defaultErrorRenderer,
    children
}: MicroFrontInShadowProps) {
    const rootRef = ref<Element>();
    const mountingRootRef = ref<Element>();

    const bootstrappedModuleRef = ref<MicroFrontBootstrappedModule>();
    const errorRef = ref<Error>();

    onMounted(async () => {
        try {
            moveToShadow(rootRef.value!);
            bootstrappedModuleRef.value = await bootstrap({ route, root: rootRef.value });
            const { mount } = bootstrappedModuleRef.value;
            await mount(mountingRootRef.value!);
        } catch (error) {
            console.error(error);
            errorRef.value = error;
        }
    });

    onBeforeUnmount(async () => {
        if (!bootstrappedModuleRef.value || !mountingRootRef.value) return;

        const { unmount } = bootstrappedModuleRef.value;
        await unmount(mountingRootRef.value);
        mountingRootRef.value = undefined;
    });

    return () => (
        <div ref={rootRef} role="document" aria-atomic="true">
            {[errorRef.value ? renderError(errorRef.value) : children(mountingRootRef)]}
        </div>
    );
});

function defaultErrorRenderer(error: Error): ReturnType<RenderFunction> {
    throw error;
}
